worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include mime.types;

  server {
    listen 8080;
    server_name green-quest-api-staging.up.railway.app;

    location /storage/ {
      root /rails;
      autoindex off;
      gzip_static on;
      expires max;
      add_header Cache-Control "public, max-age=31536000";
      try_files $uri $uri/ @rails;
    }

    location / {
      root /rails;
      proxy_pass http://127.0.0.1:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location @rails {
      root /rails;
      proxy_pass http://127.0.0.1:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}

# http {
#   include       mime.types;
#   default_type  application/octet-stream;

#   log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
#                     '$status $body_bytes_sent "$http_referer" '
#                     '"$http_user_agent" "$http_x_forwarded_for"';
#   access_log  /var/log/nginx/access.log  main;

#   sendfile on;
#   tcp_nopush on;
#   tcp_nodelay on;
#   keepalive_timeout 65;
#   types_hash_max_size 2048;

#   include /etc/nginx/conf.d/*.conf;  # Includes all additional server block files
# }