services:
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  db:
    image: postgres:17.0
    container_name: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"
    restart: always
  web:
    build: .
    command: ["sh", "-c", "parallel --ungroup --halt now,fail=1 ::: 'nginx -g \"daemon off;\"' 'bundle exec rails s -b 0.0.0.0 -p 3000'"]
    container_name: rails
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - RAILS_ENV=${RAILS_ENV}
      - APP_HOST=${APP_HOST}
      - APP_HOST_WITH_PROTOCOL=${APP_HOST_WITH_PROTOCOL}
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - storage:/rails/storage
    depends_on:
      - db
    links:
      - mailcatcher
    ports:
      - "3000:3000"
      - "8080:8080"

volumes:
  data: {}
  storage: {}
